### PR TITLE
Updated recent submissions

### PR DESCRIPTION
**Pull request by parthshah1**
Added some recent submissions.

### CODE REVIEW

**Comment by eshon** [comment]
@parthshah1 - Is it possible to include the GitHub addresses of the bounty winners?

**Comment by parthshah1** [comment]
Sure. I will ask then and add the Github usernames.

**Comment by eshon** [comment]
> Sure. I will ask them and add the Github usernames.

I thought you might already have them! If not no worries.

**Review by eshon — APPROVED** [review]

**Comment by parthshah1** [comment]
actually, these reports were started before I joined so I don't have much clue about the usernames. I will ask them and merge them as soon as I get those. Thanks for reviewing.

**Pull request merged**
